services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    container_name: ${DB_HOST}

    volumes:
      - comunired_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - comunired

  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped

    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - comunired
      - nginx-proxy
    environment:
      VIRTUAL_HOST: api.comunired.ivancm.info
      LETSENCRYPT_HOST: api.comunired.ivancm.info
      LETSENCRYPT_EMAIL: admin@comunired.ivancm.info

volumes:
  node_modules:
  comunired_mongo:
networks:
  comunired:
  nginx-proxy:
    external: true

